FROM golang:latest  
  
MAINTAINER Arvonhuang "lixh017@163.com"  
  
WORKDIR $GOPATH/src/beego_blog  
ADD ./beego_blog/ $GOPATH/src/beego_blog  
#WORKDIR $GOPATH/src/beego_blog  
 
RUN go get github.com/astaxie/beedb && go get github.com/astaxie/beego && go get github.com/astaxie/beego/orm && go get github.com/astaxie/beego/toolbox   
RUN go get github.com/ziutek/mymysql/godrv  
  
RUN go build ./main.go  
  
EXPOSE 9090   
  
#ENTRYPOINT ["./main"]  
